name: Deploy GitHub Pages
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
  push:
    branches: main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
permissions:
  pages: write
  id-token: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
        with:
          enablement: true
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2